#!/bin/bash

TAR_GZ="PhpStorm-2018.1.3.tar.gz"
INST_DIR="/opt/jetbrains/phpstorm"

if [ ! -d "$INST_DIR" ];
then
    mkdir -p "$INST_DIR"
fi

tar -xf "$HOME/$TAR_GZ" -C "$INST_DIR" --strip-components=1
